services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: my-app
    environment:
      DATABASE_URL: "postgresql://dev_user:dev_password@postgres-dev:5432/dev_db"
      NODE_ENV: development
      JWT_SECRET: "filmedadisney"
      JWT_EXPIRES_IN: "1h"
    depends_on:
      - postgres-dev
    ports:
      - "3333:3333"

volumes:
  postgres-dev-data: